version: '3.1'

services:
  web:
    build: .
    environment:
      DB_NAME: app-db
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: app-user
      DB_PASSWORD: p@ssword
    ports:
      - "80:3001"
    depends_on:
      - database
  database:
    image: postgres:14.7
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: app-user
      POSTGRES_PASSWORD: p@ssword
