version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  node: circleci/node@5.1.0

commands:
  rotate-secrets-command:
    parameters:
      config_file_path:
        type: string
    description: "rotate secrets"
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - node/install:
          install-yarn: true
          node-version: '14.18.1'
      - run: node --version
      - add_ssh_keys:
          fingerprints:
            - "41:c8:89:e5:11:03:35:86:f8:77:a5:1e:5c:f6:be:1a"
      - run:
          name: rotate secrets
          command: |
            bash ./scripts/rotate-secrets.sh <<parameters.config_file_path>>

jobs:
  rotate-secrets:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:202010-01
    steps:
#      - aws-cli/setup
#      - run:
#          name: Get and Set AWS Session Token
#          command: |
#            export AWS_SESSION_TOKEN=$(aws sts get-session-token --duration-seconds 3600 --output text --query 'Credentials.SessionToken')
#            echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $BASH_ENV
#            source $BASH_ENV
      - rotate-secrets-command:
          config_file_path: "../secrets-rotator-configs/aws-secrets-manager-config.json"
      - store_artifacts:
          path: report.encrypted
  sync-secrets-to-ssm:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: Sync Secrets to SSM Parameter Store
          command: |
            secret_value=$(aws secretsmanager get-secret-value --secret-id "$SECRET_KEY" --query 'SecretString' --output text)
            aws ssm put-parameter --name ROTATOR_TEST --value "$secret_value" --type SecureString --overwrite

workflows:
  rotate-workflow:
    jobs:
      - hold-secrets-rotation:
          type: approval
      - rotate-secrets:
          requires:
            - hold-secrets-rotation
