version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  node: circleci/node@5.1.0

commands:
  rotate-secrets-command:
    parameters:
      config_file_path:
        type: string
    description: "rotate secrets"
    steps:
#      - aws-cli/setup
      - checkout
      - attach_workspace:
          at: ~/repo
      - node/install:
          install-yarn: true
          node-version: '14.18.1'
      - run: node --version
      - add_ssh_keys:
          fingerprints:
            - "41:c8:89:e5:11:03:35:86:f8:77:a5:1e:5c:f6:be:1a"
      - run:
          name: rotate secrets
          command: |
#            export AWS_SESSION_TOKEN=$(aws sts get-session-token --duration-seconds 3600 --output text --query 'Credentials.SessionToken')
            bash ./scripts/rotate-secrets.sh <<parameters.config_file_path>>
      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data "{\"cards\":[{\"header\":{\"title\":\"Secret Rotator - Oops. ${CIRCLE_JOB} failed.\",\"imageUrl\":\"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"content\":\"secret rotation failed\",\"contentMultiline\":\"true\",\"onClick\": {\"openLink\": {\"url\": \"${CIRCLE_BUILD_URL}/\"}}}}]}]}],\"thread\":{\"name\":\"spaces/AAAAnHUlyOQ/threads/bGDnR4-DnPM\"}}"
            $CHAT_WEBHOOK_URL
      - run:
          name: Chat Notification Success
          when: on_success
          command: >
            curl --header "Content-Type: application/json" --request POST --data "{\"cards\":[{\"header\":{\"title\":\"Request service - ${CIRCLE_JOB} successful.\",\"imageUrl\":\"https://png.pngtree.com/svg/20170510/success_404253.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"content\":\"secret rotation success\",\"contentMultiline\":\"true\",\"onClick\": {\"openLink\": {\"url\": \"${CIRCLE_BUILD_URL}/\"}}}}]}]}],\"thread\":{\"name\":\"spaces/AAAAnHUlyOQ/threads/bGDnR4-DnPM\"}}" $CHAT_WEBHOOK_URL


jobs:
  rotate-ssm-key:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:202010-01
    steps:
#      - aws-cli/setup
#      - run:
#          name: Get and Set AWS Session Token
#          command: |
#            export AWS_SESSION_TOKEN=$(aws sts get-session-token --duration-seconds 3600 --output text --query 'Credentials.SessionToken')
#            echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $BASH_ENV
#            source $BASH_ENV
      - rotate-secrets-command:
          config_file_path: "../secrets-rotator-configs/config.json"
      - store_artifacts:
          path: report.encrypted

workflows:
  rotate-workflow:
    jobs:
      - hold-secret-rotation:
          type: approval
      - rotate-ssm-key:
          requires:
            - hold-secret-rotation
