postgres_defaults: &postgres_defaults
  adapter: postgresql
  encoding: utf8
  xa: false
  pool: 10
  host: localhost
  port: 5436
  username: app-user
  password: p@ssword

development:
  <<: *postgres_defaults
  database: app-db

test:
  <<: *postgres_defaults
  database: app-db

production:
  <<: *postgres_defaults
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
